app:
  experimental:
    packages: 'all' # âœ¨

  routes:
    bindings:
      catalog.viewTechDoc: techdocs.docRoot
      catalog.createComponent: catalog-import.importPage
      org.catalogIndex: catalog.catalogIndex

  extensions:
    # - apis.plugin.graphiql.browse.gitlab: true
    # - graphiql-endpoint:graphiql/gitlab: true

    # Pages
    - page:catalog/entity:
        config:
          groups:
            # placing a tab at the beginning
            - overview:
                title: Overview
            # example disabling a default group
            # - development: false
            # example overriding a default group title
            - documentation:
                title: Docs
            - deployment:
                title: Deployments
            # example adding a new group
            - custom:
                title: Custom

    # Entity page cards
    - entity-card:catalog/about:
        config:
          type: info
    - entity-card:catalog/labels
    - entity-card:catalog/links:
        config:
          filter:
            kind: component
            metadata.links:
              $exists: true
          # filter: kind:component has:links
          type: info
    # - entity-card:linguist/languages
    - entity-card:catalog-graph/relations:
        config:
          height: 300
    - entity-card:api-docs/has-apis
    - entity-card:api-docs/consumed-apis
    - entity-card:api-docs/provided-apis
    - entity-card:api-docs/providing-components
    - entity-card:api-docs/consuming-components
    # Org Plugin
    - entity-card:org/group-profile
    - entity-card:org/members-list
    - entity-card:org/ownership
    - entity-card:org/user-profile
    # - entity-card:azure-devops/readme

    # Entity page contents
    - entity-content:catalog/overview:
        config:
          group: overview
    - entity-content:api-docs/definition
    - entity-content:api-docs/apis:
        config:
          # example associating with a default group
          group: documentation
    - entity-content:techdocs:
        config:
          group: documentation
    - entity-content:kubernetes/kubernetes:
        config:
          # example disassociating with a default group
          group: false
    # - entity-content:azure-devops/pipelines
    # - entity-content:azure-devops/pull-requests
    # - entity-content:azure-devops/git-tags

  # scmAuthExtension: >-
  #   createScmAuthExtension({
  #     id: 'apis.scmAuth.addons.ghe',
  #     factory({ bind }) {
  #       bind.scmAuthAddon({
  #         baseUrl: 'https://github.spotify.net',
  #         api: githubAuthApiRef,
  #       })
  #     }
  #   })

  # externalRouteRefs:
  # bind(catalogPlugin.externalRoutes, {
  #   createComponent: scaffolderPlugin.routes.root,
  #   viewTechDoc: techdocsPlugin.routes.docRoot,
  #   createFromTemplate: scaffolderPlugin.routes.selectedTemplate,
  # });
  # bind(apiDocsPlugin.externalRoutes, {
  #   registerApi: catalogImportPlugin.routes.importPage,
  # });
  # bind(scaffolderPlugin.externalRoutes, {
  #   registerComponent: catalogImportPlugin.routes.importPage,
  #   viewTechDoc: techdocsPlugin.routes.docRoot,
  # });
  # bind(orgPlugin.externalRoutes, {
  #   catalogIndex: catalogPlugin.routes.catalogIndex,
  # });

  # extensions:
  # - plugin.catalog:
  #     config:
  #       externalRoutes:
  #         createComponent: plugin.scaffolder.page
  #         viewTechDoc: plugin.techdocs.docRootPage
  #         createFromTemplate: plugin.scaffolder.templatePage
  # - graphiql.page:
  #     config:
  #       path: /
  # - apis.auth.providers.github:
  #     config:
  #       provider: ghe

  # - core.signInPage:
  #     props:
  #       provider:
  #         id: google
  #         title: Google
  #         message: Sign In using Google
  #         apiRef: googleAuthApiRef # ???

  # - core.nav:
  #     config:
  #       logo: assets/logo.png
  #       layout:
  #       - label: Search
  #         icon: search
  #         to: /search
  #         items:
  #         - point: search
  #       - type: divider
  #       - label: Menu
  #         icon: menu
  #         items:
  #         - label: Home
  #           icon: home
  #           to: /catalog
  #         - label: Create...
  #           icon: create
  #           to: /create
  #         - type: divider
  #         - type: scroll-wrapper
  #           items:
  #           - label: Tech Radar
  #             icon: map
  #             to: /tech-radar
  #           - label: GraphiQL
  #             icon: graphiql
  #             to: /graphiql
  #         - type: divider
  #         - point: shortcuts
  #       - type: space
  #       - type: divider
  #       - label: Settings
  #         icon: avatar
  #         to: /settings
  #         items:
  #         - point: settings
  # - core.nav/search: '@backstage/plugin-search#SidebarSearchModal'
  # - core.nav/shortcuts:
  #     use: '@backstage/plugin-shortcuts#Shortcuts'
  #     config:
  #       allowExternalLinks: true
  # - core.nav/settings: '@backstage/plugin-user-settings#SidebarSettings'

  # - core.pages.index:
  #     at:
  #       point: core.routes
  #       config:
  #         path: /
  #     use: 'react-router-dom#Navigate'
  #     config:
  #       to: /catalog

  # - scaffolder.page:
  #     config:
  #       groups:
  #       - title: Recommended
  #         filter:
  #           entity.metadata.tags: recommended
  # - scaffolder.page/fields: '@backstage/plugin-scaffolder#LowerCaseValuePickerFieldExtension'
  # - scaffolder.page/layout: '@backstage/plugin-scaffolder#TwoColumnLayout'

  # - search.page/content: 'app#customSearchPage' # custom search page from somewhere

  # - user-settings.page.routes.advanced:
  #     at:
  #       point: user-settings.page/routes
  #       config:
  #         title: Advanced
  #         path: /advanced
  #       use: '@backstage/plugin-user-settings#AdvancedSettings'

  # - entity.card.orphanWarning
  # - entity.card.processingErrors
  # - entity.card.about
  # - entity.card.catalogGraph
  # - entity.card.pagerDuty
  # - entity.card.links
  # - entity.card.labels
  # - entity.card.githubInsightsLanguages
  # - entity.card.githubInsightsReleases
  # - entity.card.githubInsightsReadme:
  #     config:
  #       maxHeight: 350 # Throwing this config in to have an example, but in practice rely on default
  # - entity.card.subcomponentsCard
  # - entity.card.userProfile
  # - entity.card.ownership
  # - entity.card.likeDislikeRatings
  # - entity.content.dependsOnComponents
  # - entity.content.codeInsights
  # - entity.content.todo
  # - entity.content.feedbackResponse
