apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backstage
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
  labels:
    department: cloudengineering
    project: developerautomation
    app: backstage
    component: ingress
spec:
  rules:
  - host: backstage.dfds.cloud
    http:
      paths:
      - backend:
          serviceName: backstage
          servicePort: frontend
        path: /
      - backend:
          serviceName: backstage-backend
          servicePort: backend
        path: /backend
