apiVersion: v1
kind: Secret
data:
  db_connstring: $(DATABASE_CONNECTIONSTRING)
metadata:
  name: backstage-credentials
  namespace: backstage
type: Opaque

---
apiVersion: v1
kind: Secret
data:
  azuredevops_token: $(System.AccessToken)
  github_token: $(THIRDPARTY_GITHUB_TOKEN)
metadata:
  name: backstage-third-party-credentials
  namespace: backstage
type: Opaque