site_name: 'Backstage'
site_description: 'Main documentation for Backstage features and platform APIs'

plugins:
  - techdocs-core

nav:
  - Overview:
      - What is Backstage?: 'overview/what-is-backstage.md'
      - Backstage architecture: 'overview/architecture-overview.md'
      - Roadmap: 'overview/roadmap.md'
      - Vision: 'overview/vision.md'
      - The Spotify story: 'overview/background.md'
      - Strategies for adopting: 'overview/adopting.md'
      - Logo assets: 'overview/logos.md'
  - Getting started:
      - Getting Started: 'getting-started/index.md'
      - Running Backstage locally: 'getting-started/running-backstage-locally.md'
      - Local development: 'getting-started/development-environment.md'
      - Demo deployment: https://backstage-demo.roadie.io
      - Production deployments:
          - Create an App: 'getting-started/create-an-app.md'
          - App configuration:
              - Configuring App with plugins: 'getting-started/configure-app-with-plugins.md'
              - Customize the look-and-feel of your App: 'getting-started/app-custom-theme.md'
          - Deployment scenarios:
              - Kubernetes: 'getting-started/deployment-k8s.md'
              - Kubernetes and Helm: 'getting-started/deployment-helm.md'
              - Other: 'getting-started/deployment-other.md'
  - Features:
      - Software Catalog:
          - Overview: 'features/software-catalog/index.md'
          - Installation: 'features/software-catalog/installation.md'
          - Configuration: 'features/software-catalog/configuration.md'
          - System model: 'features/software-catalog/system-model.md'
          - YAML File Format: 'features/software-catalog/descriptor-format.md'
          - Entity References: 'features/software-catalog/references.md'
          - Well-known Annotations: 'features/software-catalog/well-known-annotations.md'
          - Extending the model: 'features/software-catalog/extending-the-model.md'
          - External integrations: 'features/software-catalog/external-integrations.md'
          - API: 'features/software-catalog/api.md'
      - Software creation templates:
          - Overview: 'features/software-templates/index.md'
          - Installation: 'features/software-templates/installation.md'
          - Adding templates: 'features/software-templates/adding-templates.md'
          - Extending the Scaffolder:
              - Overview: 'features/software-templates/extending/index.md'
              - Create your own Templater: 'features/software-templates/extending/create-your-own-templater.md'
              - Create your own Publisher: 'features/software-templates/extending/create-your-own-publisher.md'
              - Create your own Preparer: 'features/software-templates/extending/create-your-own-preparer.md'
      - Backstage Search:
          - Overview: 'features/search/README.md'
          - Architecture: 'features/search/architecture.md'
      - TechDocs:
          - Overview: 'features/techdocs/README.md'
          - Getting Started: 'features/techdocs/getting-started.md'
          - Concepts: 'features/techdocs/concepts.md'
          - TechDocs Architecture: 'features/techdocs/architecture.md'
          - Creating and Publishing Documentation: 'features/techdocs/creating-and-publishing.md'
          - Configuration: 'features/techdocs/configuration.md'
          - Using Cloud Storage: 'features/techdocs/using-cloud-storage.md'
          - HOW TO guides: 'features/techdocs/how-to-guides.md'
          - Troubleshooting: 'features/techdocs/troubleshooting.md'
          - FAQ: 'features/techdocs/FAQ.md'
      - Kubernetes:
          - Overview: 'features/kubernetes/index.md'
  - Plugins:
      - Overview: 'plugins/index.md'
      - Existing plugins: 'plugins/existing-plugins.md'
      - Creating a new plugin: 'plugins/create-a-plugin.md'
      - Developing a plugin: 'plugins/plugin-development.md'
      - Structure of a plugin: 'plugins/structure-of-a-plugin.md'
      - Composability System Migration: 'plugins/composability.md'
      - Backends and APIs:
          - Proxying: 'plugins/proxying.md'
          - Backstage backend plugin: 'plugins/backend-plugin.md'
          - Call existing API: 'plugins/call-existing-api.md'
      - Testing:
          - Overview: 'plugins/testing.md'
      - Publishing:
          - Open source and npm: 'plugins/publishing.md'
          - Private/internal (non-open source): 'plugins/publish-private.md'
          - Observability: 'plugins/observability.md'
  - Configuration:
      - Overview: 'conf/index.md'
      - Reading Configuration: 'conf/reading.md'
      - Writing Configuration: 'conf/writing.md'
      - Defining Configuration: 'conf/defining.md'
  - Authentication and identity:
      - Overview: 'auth/index.md'
      - Add auth provider: 'auth/add-auth-provider.md'
      - Auth backend: 'auth/auth-backend.md'
      - Auth backend class structure: 'auth/auth-backend-classes.md'
      - OAuth: 'auth/oauth.md'
      - Glossary: 'auth/glossary.md'
  - Designing for Backstage:
      - Backstage Design Language System (DLS): 'dls/design.md'
      - Storybook -- reusable UI components: 'http://backstage.io/storybook'
      - Contributing to Storybook: 'dls/contributing-to-storybook.md'
      - Figma resources: 'dls/figma.md'
  - API references:
      - TypeScript APIs:
          - Utilities: 'api/utility-apis.md'
          - createPlugin: 'reference/createPlugin.md'
          - createPlugin-feature-flags: 'reference/createPlugin-feature-flags.md'
          - createPlugin-router: 'reference/createPlugin-router.md'
      - Backend APIs:
          - Backend: 'api/backend.md'
  - Tutorials:
      - Overview: 'tutorials/index.md'
  - Architecture Decision Records (ADRs):
      - Overview: 'architecture-decisions/index.md'
      - ADR001 - Architecture Decision Record (ADR) log: 'architecture-decisions/adr001-add-adr-log.md'
      - ADR002 - Default Software Catalog File Format: 'architecture-decisions/adr002-default-catalog-file-format.md'
      - ADR003 - Avoid Default Exports and Prefer Named Exports: 'architecture-decisions/adr003-avoid-default-exports.md'
      - ADR004 - Module Export Structure: 'architecture-decisions/adr004-module-export-structure.md'
      - ADR005 - Catalog Core Entities: 'architecture-decisions/adr005-catalog-core-entities.md'
      - ADR006 - Avoid React.FC and React.SFC: 'architecture-decisions/adr006-avoid-react-fc.md'
      - ADR007 - Use MSW for Network Request Mocking: 'architecture-decisions/adr007-use-msw-to-mock-service-requests.md'
      - ADR008 - Default Catalog File Name: 'architecture-decisions/adr008-default-catalog-file-name.md'
      - ADR009 - Entity References: 'architecture-decisions/adr009-entity-references.md'
      - ADR010 - Luxon Date Library: 'architecture-decisions/adr010-luxon-date-library.md'
      - ADR011 - Plugin Package Structure: 'architecture-decisions/adr011-plugin-package-structure.md'
  - Contribute: '../CONTRIBUTING.md'
  - Support:
      - 'support/support.md'
      - 'support/project-structure.md'
  - Glossary: glossary.md
  - FAQ: FAQ.md
