site_name: 'Backstage'
site_description: 'Main documentation for Backstage features and platform APIs'

plugins:
  - techdocs-core

nav:
  - Overview:
      - What is Backstage?: 'overview/what-is-backstage.md'
      - Architecture overview: 'overview/architecture-overview.md'
      - Project Roadmap: 'overview/roadmap.md'
      - Vision: 'overview/vision.md'
      - The Spotify Story: 'overview/background.md'
      - Strategies for adopting: 'overview/adopting.md'
      - Stability Index: 'overview/stability-index.md'
      - Support and community: 'overview/support.md'
      - Glossary: 'overview/glossary.md'
      - Logo assets: 'overview/logos.md'
  - Getting Started:
      - Getting Started: 'getting-started/index.md'
      - Create an App: 'getting-started/create-an-app.md'
      - Running Backstage locally: 'getting-started/running-backstage-locally.md'
      - App configuration:
          - Configuring App with plugins: 'getting-started/configure-app-with-plugins.md'
          - Customize the look-and-feel of your App: 'getting-started/app-custom-theme.md'
      - Keeping Backstage Updated: 'getting-started/keeping-backstage-updated.md'
      - Key Concepts: 'getting-started/concepts.md'
      - Contributors: 'getting-started/contributors.md'
      - Project Structure: 'getting-started/project-structure.md'
  - CLI:
      - Overview: 'cli/index.md'
      - Commands: 'cli/commands.md'
  - Core Features:
      - Software Catalog:
          - Overview: 'features/software-catalog/index.md'
          - The Life of an Entity: 'features/software-catalog/life-of-an-entity.md'
          - Catalog Configuration: 'features/software-catalog/configuration.md'
          - System Model: 'features/software-catalog/system-model.md'
          - YAML File Format: 'features/software-catalog/descriptor-format.md'
          - Entity References: 'features/software-catalog/references.md'
          - Well-known Annotations: 'features/software-catalog/well-known-annotations.md'
          - Well-known Relations: 'features/software-catalog/well-known-relations.md'
          - Well-known Statuses: 'features/software-catalog/well-known-statuses.md'
          - Extending the model: 'features/software-catalog/extending-the-model.md'
          - External integrations: 'features/software-catalog/external-integrations.md'
          - Catalog Customization: 'features/software-catalog/catalog-customization.md'
          - API: 'features/software-catalog/api.md'
      - Kubernetes:
          - Overview: 'features/kubernetes/index.md'
          - Installation: 'features/kubernetes/installation.md'
          - Configuration: 'features/kubernetes/configuration.md'
          - Troubleshooting: 'features/kubernetes/troubleshooting.md'
      - Software Templates:
          - Overview: 'features/software-templates/index.md'
          - Configuration: 'features/software-templates/configuration.md'
          - Adding your own Templates: 'features/software-templates/adding-templates.md'
          - Writing Templates: 'features/software-templates/writing-templates.md'
          - Builtin Actions: 'features/software-templates/builtin-actions.md'
          - Writing Custom Actions: 'features/software-templates/writing-custom-actions.md'
          - Writing Templates (Legacy): 'features/software-templates/legacy.md'
          - Migrating from v1alpha1 to v1beta2 templates: 'features/software-templates/migrating-from-v1alpha1-to-v1beta2.md'

      - Backstage Search:
          - Overview: 'features/search/README.md'
          - Getting Started: 'features/search/getting-started.md'
          - Concepts: 'features/search/concepts.md'
          - Search Architecture: 'features/search/architecture.md'
          - Search Engines: 'features/search/search-engines.md'
      - TechDocs:
          - Overview: 'features/techdocs/README.md'
          - Getting Started: 'features/techdocs/getting-started.md'
          - Concepts: 'features/techdocs/concepts.md'
          - TechDocs Architecture: 'features/techdocs/architecture.md'
          - Creating and Publishing Documentation: 'features/techdocs/creating-and-publishing.md'
          - TechDocs Configuration Options: 'features/techdocs/configuration.md'
          - Using Cloud Storage: 'features/techdocs/using-cloud-storage.md'
          - Configuring CI/CD to generate and publish TechDocs sites: 'features/techdocs/configuring-ci-cd.md'
          - HOW TO guides: 'features/techdocs/how-to-guides.md'
          - Troubleshooting: 'features/techdocs/troubleshooting.md'
          - FAQ: 'features/techdocs/FAQ.md'
  - Integrations:
      - Overview: 'integrations/index.md'
      - AWS S3:
          - Locations: 'integrations/aws-s3/locations.md'
          - Discovery: 'integrations/aws-s3/discovery.md'
      - Azure:
          - Locations: 'integrations/azure/locations.md'
          - Org Data: 'integrations/azure/org.md'
      - Bitbucket:
          - Locations: 'integrations/bitbucket/locations.md'
          - Discovery: 'integrations/bitbucket/discovery.md'
      - Datadog:
          - Installation: 'integrations/datadog-rum/installation.md'
      - GitHub:
          - Locations: 'integrations/github/locations.md'
          - Discovery: 'integrations/github/discovery.md'
          - Org Data: 'integrations/github/org.md'
      - GitLab:
          - Locations: 'integrations/gitlab/locations.md'
      - Google Analytics:
          - Installation: 'integrations/google-analytics/installation.md'
      - Google GCS:
          - Locations: 'integrations/google-cloud-storage/locations.md'
      - LDAP:
          - Org Data: 'integrations/ldap/org.md'
  - Plugins:
      - Intro to plugins: 'plugins/index.md'
      - Existing plugins: 'plugins/existing-plugins.md'
      - Create a Backstage Plugin: 'plugins/create-a-plugin.md'
      - Plugin Development: 'plugins/plugin-development.md'
      - Structure of a plugin: 'plugins/structure-of-a-plugin.md'
      - Plugin Development: 'plugins/plugin-development.md'
      - Integrate into the Software Catalog: 'plugins/integrating-plugin-into-software-catalog.md'
      - Composability System Migration: 'plugins/composability.md'
      - Backends and APIs:
          - Proxying: 'plugins/proxying.md'
          - Backend plugin: 'plugins/backend-plugin.md'
          - Call existing API: 'plugins/call-existing-api.md'
          - GitHub Apps for Backend Authentication: 'plugins/github-apps.md'
          - URL Reader: 'plugins/url-reader.md'
      - Testing:
          - Testing with Jest: 'plugins/testing.md'
      - Publishing:
          - Publishing: 'plugins/publishing.md'
          - Publish private: 'plugins/publish-private.md'
          - Add to Marketplace: 'plugins/add-to-marketplace.md'
          - Observability: 'plugins/observability.md'
  - Configuration:
      - Static Configuration in Backstage: 'conf/index.md'
      - Reading Backstage Configuration: 'conf/reading.md'
      - Writing Backstage Configuration: 'conf/writing.md'
      - Defining Configuration for your Plugin: 'conf/defining.md'
  - Authentication and identity:
      - Adding Authentication: 'auth/index.md'
      - Included providers:
          - Auth0: 'auth/auth0/provider.md'
          - Azure: 'auth/microsoft/provider.md'
          - GitHub: 'auth/github/provider.md'
          - GitLab: 'auth/gitlab/provider.md'
          - Google: 'auth/google/provider.md'
          - Okta: 'auth/okta/provider.md'
          - OneLogin: 'auth/onelogin/provider.md'
      - Adding authentication providers: 'auth/add-auth-provider.md'
      - Using authentication and identity: 'auth/using-auth.md'
      - Sign in resolvers: 'auth/identity-resolver.md'
      - Auth backend: 'auth/auth-backend.md'
      - OAuth and OpenID Connect: 'auth/oauth.md'
      - Auth backend classes: 'auth/auth-backend-classes.md'
      - Glossary: 'auth/glossary.md'
  - Deployment:
      - Deploying Backstage: 'deployment/index.md'
      - Docker: 'deployment/docker.md'
      - Kubernetes: 'deployment/k8s.md'
      - Helm: 'deployment/helm.md'
      - Heroku: 'deployment/heroku.md'
  - Designing for Backstage:
      - Design: 'dls/design.md'
      - Contributing to Storybook: 'dls/contributing-to-storybook.md'
      - Figma: 'dls/figma.md'
  - API Reference:
      - Guides:
          - Utility APIs: 'api/utility-apis.md'
  - Tutorials:
      - Future developer journey: 'tutorials/journey.md'
      - Migrating away from @backstage/core: 'tutorials/migrating-away-from-core.md'
      - Adding Custom Plugin to Existing Monorepo App: 'tutorials/quickstart-app-plugin.md'
      - Switching Backstage from SQLite to PostgreSQL: 'tutorials/switching-sqlite-postgres.md'
  - Architecture Decision Records (ADRs):
      - Overview: 'architecture-decisions/index.md'
      - ADR001 - Architecture Decision Record (ADR) log: 'architecture-decisions/adr001-add-adr-log.md'
      - ADR002 - Default Software Catalog File Format: 'architecture-decisions/adr002-default-catalog-file-format.md'
      - ADR003 - Avoid Default Exports and Prefer Named Exports: 'architecture-decisions/adr003-avoid-default-exports.md'
      - ADR004 - Module Export Structure: 'architecture-decisions/adr004-module-export-structure.md'
      - ADR005 - Catalog Core Entities: 'architecture-decisions/adr005-catalog-core-entities.md'
      - ADR006 - Avoid React.FC and React.SFC: 'architecture-decisions/adr006-avoid-react-fc.md'
      - ADR007 - Use MSW for Network Request Mocking: 'architecture-decisions/adr007-use-msw-to-mock-service-requests.md'
      - ADR008 - Default Catalog File Name: 'architecture-decisions/adr008-default-catalog-file-name.md'
      - ADR009 - Entity References: 'architecture-decisions/adr009-entity-references.md'
      - ADR010 - Luxon Date Library: 'architecture-decisions/adr010-luxon-date-library.md'
      - ADR011 - Plugin Package Structure: 'architecture-decisions/adr011-plugin-package-structure.md'
  - Support:
      - Backstage Project Structure: 'support/project-structure.md'
  - Glossary: glossary.md
  - FAQ: FAQ.md
