site_name: 'Backstage'
site_description: 'Main documentation for Backstage features and platform APIs'

nav:
  - Overview:
      - What is Backstage?: 'overview/what-is-backstage.md'
      - Architecture and terminology: 'overview/architecture-terminology.md'
      - Roadmap: 'overview/roadmap.md'
  - Getting started:
      - Running Backstage locally: 'getting-started/index.md'
      - Installation: 'getting-started/installation.md'
      - Local development: 'getting-started/development-environment.md'
      - Demo deployment: https://backstage-demo.roadie.io
      - Production deployments:
          - Create an App: 'getting-started/create-an-app.md'
          - App configuration:
              - Configuring App with plugins: 'getting-started/configure-app-with-plugins.md'
              - Customize the look-and-feel of your App: 'getting-started/customize-app-look-and-feel.md'
          - Deployment scenarios:
              - Kubernetes: 'getting-started/deployment-k8s.md'
              - Other: 'getting-started/deployment-other.md'
  - Features:
      - Software Catalog:
          - Overview: 'features/software-catalog/index.md'
          - System model: 'features/software-catalog/system-model.md'
          - YAML File Format: 'features/software-catalog/descriptor-format.md'
          - Populating the catalog: 'features/software-catalog/populating.md'
          - Extending the model: 'features/software-catalog/extending-the-model.md'
          - External integrations: 'features/software-catalog/external-integrations.md'
          - API: 'features/software-catalog/api.md'
      - Software creation templates:
          - Overview: 'features/software-templates/index.md'
          - Configure templates: 'features/software-templates/configure-templates.md'
          - Adding templates: 'features/software-templates/adding-templates.md'
          - Extending the Scaffolder:
              - Overview: 'features/software-templates/extending/index.md'
              - Create your own Templater: 'features/software-templates/extending/create-your-own-templater.md'
              - Create your own Publisher: 'features/software-templates/extending/create-your-own-publisher.md'
              - Create your own Preparer: 'features/software-templates/extending/create-your-own-preparer.md'
      - Docs-like-code:
          - Overview: 'features/techdocs/README.md'
          - Getting Started: 'features/techdocs/getting-started.md'
          - Concepts: 'features/techdocs/concepts.md'
          - Reading Documentation: 'features/techdocs/reading-documentation.md'
          - Writing Documentation: 'features/techdocs/writing-documentation.md'
          - Publishing Documentation: 'features/techdocs/publishing-documentation.md'
          - Contributing: 'features/techdocs/contributing.md'
          - Debugging: 'features/techdocs/debugging.md'
          - FAQ: 'features/techdocs/FAQ.md'
  - Plugins:
      - Overview: 'plugins/index.md'
      - Existing plugins: 'plugins/existing-plugins.md'
      - Creating a new plugin: 'plugins/create-a-plugin.md'
      - Developing a plugin: 'plugins/developing-plugins.md'
      - Structure of a plugin: 'plugins/structure-of-a-plugin.md'
      - Backends and APIs:
          - Proxying: 'plugins/proxying.md'
          - Backstage backend plugin: 'plugins/backend-plugin.md'
          - Call existing API: 'plugins/call-existing-api.md'
      - Testing:
          - Overview: 'plugins/testing.md'
      - Publishing:
          - Open source and NPM: 'plugins/publishing.md'
          - Private/internal (non-open source): 'plugins/publish-private.md'
  - Authentication and identity:
      - Overview: 'auth/index.md'
      - Add auth provider: 'auth/add-auth-provider.md'
      - Auth backend: 'auth/auth-backend.md'
      - OAuth: 'auth/oauth.md'
      - Glossary: 'auth/glossary.md'
  - Designing for Backstage:
      - Backstage Design Language System (DLS): 'dls/design.md'
      - Storybook -- reusable UI components: 'dls/storybook.md'
      - Contributing to Storybook: 'dls/contributing-to-storybook.md'
      - Figma resources: 'dls/figma.md'
  - API references:
      - TypeScript APIs:
          - Utilities: 'api/utility-apis.md'
          - createPlugin: 'reference/createPlugin.md'
          - createPlugin-feature-flags: 'reference/createPlugin-feature-flags.md'
          - createPlugin-router: 'reference/createPlugin-router.md'
      - Backend APIs:
          - Backend: 'api/backend.md'
  - Tutorials:
      - Overview: 'tutorials/index.md'
  - Architecture Decision Records (ADRs):
      - Overview: 'architecture-decisions/index.md'
      - ADR001 - Architecture Decision Record (ADR) log: 'architecture-decisions/adr001-add-adr-log.md'
      - ADR002 - Default Software Catalog File Format: 'architecture-decisions/adr002-default-catalog-file-format.md'
      - ADR003 - Avoid Default Exports and Prefer Named Exports: 'architecture-decisions/adr003-avoid-default-exports.md'
      - ADR004 - Module Export Structure: 'architecture-decisions/adr004-module-export-structure.md'
      - ADR005 - Catalog Core Entities: 'architecture-decisions/adr005-catalog-core-entities.md'
      - ADR006 - Avoid React.FC and React.SFC: 'architecture-decisions/adr006-avoid-react-fc.md'
  - Contribute: '../CONTRIBUTING.md'
  - Support: 'overview/support.md'
  - FAQ: FAQ.md

plugins:
  - techdocs-core
