app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: Acme Corporation

backend:
  baseUrl: http://localhost:7000
  listen: 0.0.0.0:7000
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true

proxy:
  '/test':
    target: 'https://example.com'
    changeOrigin: true

techdocs:
  storageUrl: https://techdocs-mock-sites.storage.googleapis.com

auth:
  providers: {}

catalog:
  locations:
    # Backstage Example Component
    - type: github
      target: https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/artist-lookup-component.yaml
    - type: github
      target: https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/playback-order-component.yaml
    - type: github
      target: https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/podcast-api-component.yaml
    - type: github
      target: https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/queue-proxy-component.yaml
    - type: github
      target: https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/searcher-component.yaml
    - type: github
      target: https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/playback-lib-component.yaml
    - type: github
      target: https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/www-artist-component.yaml
    - type: github
      target: https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/shuffle-api-component.yaml

    # Backstage Example Templates
    - type: github
      target: https://github.com/spotify/backstage/blob/master/plugins/scaffolder-backend/sample-templates/react-ssr-template/template.yaml
    - type: github
      target: https://github.com/spotify/backstage/blob/master/plugins/scaffolder-backend/sample-templates/springboot-grpc-template/template.yaml
    - type: github
      target: https://github.com/spotify/backstage/blob/master/plugins/scaffolder-backend/sample-templates/create-react-app/template.yaml
    - type: github
      target: https://github.com/spotify/cookiecutter-golang/blob/master/template.yaml
