name: Automate staleness
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *' # run every 10 minutes as it also removes labels.

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write # for actions/stale to close stale issues
      pull-requests: write # for actions/stale to close stale PRs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Stale check - base
        uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs. Thank you
            for your contributions.
          days-before-issue-stale: 60
          days-before-issue-close: 14
          exempt-issue-labels: after vacations,no stale
          stale-issue-label: stale
          stale-pr-message: >
            This PR has been automatically marked as stale because it has not had
            recent activity from the author. It will be closed if no further activity occurs.
            If the PR was closed and you want it re-opened, let us know
            and we'll re-open the PR so that you can continue the contribution!
          days-before-pr-stale: 30
          days-before-pr-close: 14
          exempt-pr-labels: after vacations,no stale
          stale-pr-label: stale
          operations-per-run: 100

      - name: Stale check - bugs without repro
        uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          stale-issue-message: >
            This bug report has been automatically marked as stale because it has not had
            recent activity and does not have valid steps to reproduce. It will be closed
            if no further activity occurs. If the PR was closed and you want it re-opened,
            let us know and we'll re-open the PR so that you can continue the contribution!
          days-before-stale: 30
          days-before-close: 7
          days-before-pr-stale: -1
          exempt-issue-labels: after vacations,no stale
          only-labels: type:bug,needs:repro
          stale-issue-label: stale
          operations-per-run: 50
