# NO-OP placeholder that always passes for other paths
# This is here so that we're able to set the status check as required

name: CI Void
on:
  pull_request:
    paths:
      - 'microsite/**'
      - 'beps/**'

permissions:
  contents: read

jobs:
  # The verify jobs runs all the verification that doesn't require a
  # diff towards master, since it takes some time to fetch that.
  verify-noop:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    name: Verify ${{ matrix.node-version }}
    steps:
      # - name: Harden Runner
      #   uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
      #   with:
      #     egress-policy: audit

      - run: echo NOOP

  test-noop:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    name: Test ${{ matrix.node-version }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - run: echo NOOP
