name: CLI Test

on:
  pull_request:
    paths:
      - '.github/workflows/cli.yml'
      - 'packages/cli/**'
      - 'packages/core/**'
      - 'yarn.lock'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12.x]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: find location of global yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: cache global yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        run: yarn install --frozen-lockfile
      - run: yarn tsc
      - run: yarn build
      - name: verify app and plugin creation on Windows
        working-directory: ${{ runner.temp }}
        if: runner.os == 'Windows'
        run: node ${{ github.workspace }}/packages/cli/e2e-test/cli-e2e-test.js
        env:
          BACKSTAGE_E2E_CLI_TEST: true
      - name: verify app and plugin creation on Linux
        working-directory: ${{ runner.temp }}
        if: runner.os == 'Linux'
        run: |
          sudo sysctl fs.inotify.max_user_watches=524288
          node ${{ github.workspace }}/packages/cli/e2e-test/cli-e2e-test.js
        env:
          BACKSTAGE_E2E_CLI_TEST: true
      - name: lint newly created app and plugin
        run: yarn lint:all
        working-directory: ${{ runner.temp }}/test-app
        env:
          BACKSTAGE_E2E_CLI_TEST: true
      - name: test newly created app and plugin
        run: yarn test:all
        working-directory: ${{ runner.temp }}/test-app
        env:
          BACKSTAGE_E2E_CLI_TEST: true
      - name: e2e test newly created app
        run: yarn test:e2e:ci
        working-directory: ${{ runner.temp }}/test-app/packages/app
        env:
          PORT: 3001
          BACKSTAGE_E2E_CLI_TEST: true
