name: Deploy Microsite
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  stable:
    runs-on: ubuntu-latest
    concurrency:
      group: stable-reference-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=8192

    outputs:
      release: ${{ steps.find-release.outputs.result }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: find latest release
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        id: find-release
        with:
          script: |
            const { data } = await github.rest.repos.listTags({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100,
            })

            const [{tag}] = data
              .map(i => i.name)
              .filter(tag => tag.match(/^v\d+\.\d+\.\d+$/))
              .map(tag => ({
                tag,
                val: tag
                  .slice(1)
                  .split('.')
                  .reduce((val, part) => Number(val) * 1000 + Number(part))
              }))
              .sort((a, b) => b.val - a.val)

            return tag
          result-encoding: string

      - name: checkout latest release
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: refs/tags/${{ steps.find-release.outputs.result }}

      - name: Use Node.js 20.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/ # Needed for auth

      - name: yarn install
        uses: backstage/actions/yarn-install@b3c1841fd69e1658ac631afafd0fb140a2309024 # v0.6.17
        with:
          cache-prefix: ${{ runner.os }}-v20.x

      - name: build API reference
        run: yarn build:api-docs

      - name: upload API reference
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: stable-reference
          path: docs/reference/
          if-no-files-found: error
          retention-days: 1

      # Use the lower-level cache actions for the success cache, so that we can store the cache even on failed builds
      - name: restore package-docs cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: .cache/package-docs
          key: ${{ runner.os }}-v${{ matrix.node-version }}-package-docs-stable-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-v${{ matrix.node-version }}-package-docs-stable-

      - name: build API reference (beta)
        run: yarn backstage-repo-tools package-docs

      - name: upload API reference (beta)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: stable-reference-beta
          path: type-docs/
          if-no-files-found: error
          retention-days: 1

      # Always save success cache even if there were failures, that way it can be used in re-triggered builds
      - name: save package-docs cache
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        if: always()
        with:
          path: .cache/package-docs
          key: ${{ runner.os }}-v${{ matrix.node-version }}-package-docs-stable-${{ github.run_id }}

      - name: microsite yarn install
        run: yarn install --immutable
        working-directory: microsite

      - name: build OpenAPI API docs
        working-directory: microsite
        run: yarn docusaurus gen-api-docs all

      - name: upload OpenAPI API docs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: stable-openapi-docs
          path: docs/**/api/**/*
          if-no-files-found: error
          retention-days: 1

  next:
    runs-on: ubuntu-latest
    concurrency:
      group: next-reference-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=8192

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: checkout master
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Use Node.js 20.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/ # Needed for auth

      - name: yarn install
        uses: backstage/actions/yarn-install@b3c1841fd69e1658ac631afafd0fb140a2309024 # v0.6.17
        with:
          cache-prefix: ${{ runner.os }}-v20.x

      - name: build API reference
        run: yarn build:api-docs

      - name: upload API reference
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: next-reference
          path: docs/reference/
          if-no-files-found: error
          retention-days: 1

      # Use the lower-level cache actions for the success cache, so that we can store the cache even on failed builds
      - name: restore package-docs cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: .cache/package-docs
          key: ${{ runner.os }}-v${{ matrix.node-version }}-package-docs-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-v${{ matrix.node-version }}-package-docs-

      - name: build API reference (beta)
        run: yarn backstage-repo-tools package-docs

      - name: upload API reference (beta)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: next-reference-beta
          path: type-docs/
          if-no-files-found: error
          retention-days: 1

      # Always save success cache even if there were failures, that way it can be used in re-triggered builds
      - name: save package-docs cache
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        if: always()
        with:
          path: .cache/package-docs
          key: ${{ runner.os }}-v${{ matrix.node-version }}-package-docs-${{ github.run_id }}

      - name: Build Storybook
        run: yarn build-storybook

      - name: Upload Storybook
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: storybook
          path: dist-storybook
          if-no-files-found: error
          retention-days: 1

      - name: microsite yarn install
        run: yarn install --immutable
        working-directory: microsite

      - name: build OpenAPI API docs
        working-directory: microsite
        run: yarn docusaurus gen-api-docs all

      - name: upload OpenAPI API docs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: next-openapi-docs
          path: docs/**/api/**/*
          if-no-files-found: error
          retention-days: 1

  deploy-microsite-and-storybook:
    permissions:
      contents: write # for JamesIves/github-pages-deploy-action to push changes in repo

    runs-on: ubuntu-latest

    needs:
      - stable
      - next

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=16384
      DOCUSAURUS_SSR_CONCURRENCY: 5

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - name: Use Node.js 20.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/ # Needed for auth

      # Stable docs
      - name: checkout latest release
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: refs/tags/${{ needs.stable.outputs.release }}

      - name: microsite yarn install
        run: yarn install --immutable
        working-directory: microsite

      - name: download stable reference
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: stable-reference
          path: docs/reference

      - name: download stable OpenAPI API docs
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: stable-openapi-docs
          path: docs

      - name: grab lastest releases docs
        run: |
          git fetch origin master --depth 1
          git checkout FETCH_HEAD -- docs/releases

      - name: generate stable docs
        run: yarn docusaurus docs:version stable
        working-directory: microsite

      - name: clear generated docs
        run: git clean -fdx docs/

      # Next docs
      - name: checkout master
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          clean: false

      - name: microsite yarn install
        run: yarn install --immutable
        working-directory: microsite

      - name: download next reference
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: next-reference
          path: docs/reference

      - name: download next OpenAPI API docs
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: next-openapi-docs
          path: docs

      - name: build microsite
        run: yarn build
        working-directory: microsite

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: storybook
          path: microsite/build/storybook

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: stable-reference-beta
          path: microsite/build/api/stable/

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: next-reference-beta
          path: microsite/build/api/next/

      - name: Check the build output
        run: ls microsite/build && ls microsite/build/storybook && ls microsite/build/api/stable && ls microsite/build/api/next

      - name: Deploy both microsite and storybook to gh-pages
        uses: JamesIves/github-pages-deploy-action@4a3abc783e1a24aeb44c16e869ad83caf6b4cc23 # v4.7.4
        with:
          branch: gh-pages
          folder: microsite/build
