name: Build and push Demo image
on:
  repository_dispatch:
    types: [release-published]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: --max-old-space-size=4096
      UFFIZZI_URL: https://app.uffizzi.com

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: v${{ github.event.client_payload.version }}
          # path: backstage

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/ # Needed for auth

      - name: yarn install
        uses: backstage/actions/yarn-install@v0.6.2
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - name: Use demonstration app config with plugins
        run: |
          cp -f ./.github/demo/uffizzi.demonstration.app-config.yaml ./app-config.yaml
          cp -a ./.github/demo/packages/* ./packages/
          yarn workspace example-app add @spotify/backstage-plugin-pulse
          yarn workspace example-backend add @spotify/backstage-plugin-pulse-backend

      - name: typescript build
        run: |
          yarn tsc

      - name: backstage build
        run: |
          yarn workspace example-backend build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: packages/backend/Dockerfile
          push: true
          tags: |
            registry.uffizzi.com/${{ github.repository_owner }}/backstage:demo
          labels: |
            org.opencontainers.image.description=Demonstration image generated from the latest Backstage release; This includes some additional catalogs.
