name: Issue
on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  sync:
    permissions:
      contents: read # for github/issue-labeler to get repo contents
      issues: write # for github/issue-labeler to create or remove labels
    runs-on: ubuntu-latest

    if: github.repository == 'backstage/backstage'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - name: Add issue labels
        uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
        with:
          include-title: 1
          include-body: 0
          configuration-path: .github/issue-labeler.yml
          enable-versioned-regex: 0
          not-before: 2024-04-19T15:03:51Z
          repo-token: '${{ secrets.GITHUB_TOKEN }}'

      # These two steps add labels based on user input in the issue form
      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/.common.yaml
      - name: Add advanced issue labels
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          token: ${{ secrets.GITHUB_TOKEN }}
