# This workflow is used to trigger the "PR Review Comment" workflow. This chaining is needed
# because workflows triggered by pull_request_review_comment do not have access to secrets.

name: PR Review Comment Trigger
on:
  pull_request_review_comment:
    types:
      - created

permissions:
  contents: read

jobs:
  trigger:
    runs-on: ubuntu-latest

    # The "PR Review Comment" workflow will check the success status of this workflow and only mark
    # the PR for re-review if this workflow was successful, which is when the author leaves a review comment.
    if: github.repository == 'backstage/backstage' && github.event.comment.user.id == github.event.pull_request.user.id

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: pr_number-${{ github.event.pull_request.number }}
          path: pr/
          overwrite: true
