# This workflow is triggered by "PR Review Comment Trigger"

name: PR Review Comment
on:
  workflow_run:
    workflows: [PR Review Comment Trigger]
    types:
      - completed

jobs:
  re-review:
    runs-on: ubuntu-latest

    # The triggering workflow will report success if the PR needs re-review
    if: github.repository == 'backstage/backstage' && github.event.workflow_run.conclusion == 'success'

    steps:
      # Inspired by https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit

      - name: Read PR Number
        id: pr-number
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });
            const [artifact] = allArtifacts.data.artifacts.filter(artifact => artifact.name.startsWith('pr_number-'))
            if (!artifact) {
              throw new Error('No PR Number artifact available')
            }

            const prNumber = artifact.name.slice('pr_number-'.length)
            core.setOutput('pr-number', prNumber);

      - uses: backstage/actions/re-review@b3c1841fd69e1658ac631afafd0fb140a2309024 # v0.6.17
        with:
          app-id: ${{ secrets.BACKSTAGE_GOALIE_APPLICATION_ID }}
          private-key: ${{ secrets.BACKSTAGE_GOALIE_PRIVATE_KEY }}
          installation-id: ${{ secrets.BACKSTAGE_GOALIE_INSTALLATION_ID }}
          project-id: PVT_kwDOBFKqdc02LQ
          issue-number: ${{ steps.pr-number.outputs.pr-number }}
