name: 'Snyk Github Issue Sync'

on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Snyk report
        uses: snyk/actions/node@master
        continue-on-error: true # Snyk CLI exits with error when vulnerabilities are found
        with:
          args: >
            --yarn-workspaces
            --org=backstage-dgh
            --strict-out-of-sync=false
            --json-file-output=snyk.json
          json: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Update Github issues
        run: yarn ts-node scripts/snyk-github-issue-sync.ts
