name: Sync BUI Docs
on:
  push:
    branches: [master]

jobs:
  sync-docs-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Use Node.js 20.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/ # Needed for auth

      - name: yarn install
        uses: backstage/actions/yarn-install@b3c1841fd69e1658ac631afafd0fb140a2309024 # v0.6.17
        with:
          cache-prefix: ${{ runner.os }}-v20.x

      - name: Checkout backstage/docs-ui
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: backstage/docs-ui
          path: bui-external-docs
          token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email noreply@backstage.io
          git config --global user.name 'Github BUI Docs workflow'

      - name: Install dependencies
        working-directory: docs-ui
        run: yarn install

      - name: Build Docs UI
        working-directory: docs-ui
        run: |
          yarn build

      - name: Replace contents of bui-external-docs repo with docs build output
        working-directory: bui-external-docs
        run: |
          git rm -rf .
          cp -R ../docs-ui/dist/. .

      - name: Commit to bui-storybook repo
        working-directory: bui-external-docs
        run: |
          git add .
          git commit -am "BUI Docs build for backstage/backstage@${{ github.sha }}"
          git push
