name: Sync code formatting
on:
  push:
    branches:
      - master

jobs:
  autofix-markdown:
    name: Autofix Markdown files using Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          # Fetch changes to previous commit - required for 'only_changed' in Prettier action
          fetch-depth: 0

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/ # Needed for auth
      - name: yarn install
        uses: backstage/actions/yarn-install@3c138326f7fcbf253b88170c1f29bae8e975d47c # v0.6.14
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - name: Run Prettier on ADOPTERS.md
        uses: creyD/prettier_action@31355f8eef017f8aeba2e0bc09d8502b13dbbad1 # v4.3
        with:
          # Modifies commit only if prettier autofixed the ADOPTERS.md
          prettier_options: --config docs/prettier.config.js --write ADOPTERS.md
          only_changed: true
          commit_message: 'Autofix ADOPTERS.md using Prettier'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
