name: Sync code formatting
on:
  push:
    branches:
      - master

jobs:
  autofix-markdown:
    name: Autofix Markdown files using Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Fetch changes to previous commit - required for 'only_changed' in Prettier action
          fetch-depth: 0

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/ # Needed for auth
      - name: yarn install
        uses: backstage/actions/yarn-install@b3c1841fd69e1658ac631afafd0fb140a2309024 # v0.6.17
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - name: Run Prettier on ADOPTERS.md
        uses: creyD/prettier_action@31355f8eef017f8aeba2e0bc09d8502b13dbbad1 # v4.3
        with:
          # Modifies commit only if prettier autofixed the ADOPTERS.md
          prettier_options: --config docs/prettier.config.js --write ADOPTERS.md
          only_changed: true
          commit_message: 'Autofix ADOPTERS.md using Prettier'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
