name: Storybook
on:
  # NOTE: If you change these you must update verify_storybook-noop.yml as well
  pull_request:
    paths:
      - '.github/workflows/verify_storybook.yml'
      - 'storybook/**'
      - 'packages/config/src/**'
      - 'packages/theme/src/**'
      - 'packages/types/src/**'
      - 'packages/errors/src/**'
      - 'packages/version-bridge/src/**'
      - 'packages/test-utils/src/**'
      - 'packages/core-app-api/src/**'
      - 'packages/core-plugin-api/src/**'
      - 'packages/core-components/src/**'
      - '**/*.stories.tsx'

jobs:
  chromatic:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    name: Storybook
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0 # Required to retrieve git history

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/ # Needed for auth
      - name: yarn install
        uses: backstage/actions/yarn-install@3c138326f7fcbf253b88170c1f29bae8e975d47c # v0.6.14
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}
      - name: storybook yarn install
        run: yarn install --immutable
        working-directory: storybook

      - run: yarn build-storybook

      - uses: chromaui/action@b984808b772126a9f44b2b7737b131b68a2ede32 # v11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # projectToken intentionally shared to allow collaborators to run Chromatic on forks
          # https://www.chromatic.com/docs/custom-ci-provider#run-chromatic-on-external-forks-of-open-source-projects
          projectToken: 9tzak77m9nj
          workingDir: storybook
          storybookBuildDir: dist
