name: Accessibility
on:
  # NOTE: If you change these you must update verify_accessibility-noop.yml as well
  pull_request:
    branches: [master]
    paths:
      - 'lighthouserc.js'
      - '.github/workflows/verify_accessibility.yml'
      - 'plugins/catalog/src/**'
      - 'plugins/catalog-react/src/**'
      - 'plugins/techdocs/src/**'
      - 'plugins/techdocs-react/src/**'
      - 'plugins/scaffolder/src/**'
      - 'plugins/scaffolder-react/src/**'
      - 'plugins/search/src/**'
      - 'plugins/search-react/src/**'
jobs:
  lhci:
    name: Accessibility
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Use Node.js 18.x
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 18.x
      - name: yarn install
        uses: backstage/actions/yarn-install@3c138326f7fcbf253b88170c1f29bae8e975d47c # v0.6.14
        with:
          cache-prefix: ${{ runner.os }}-v18.x
      - name: run Lighthouse CI
        run: |
          yarn dlx @lhci/cli@0.11.x autorun
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
