# NO-OP placeholder that always passes for other paths
# This is here so that we're able to set the status check as required

name: E2E Windows Void
on:
  pull_request:
    paths-ignore:
      - 'yarn.lock'
      - '.github/workflows/verify_e2e-windows.yml'
      - 'packages/cli/**'
      - 'packages/e2e-test/**'
      - 'packages/create-app/**'

permissions:
  contents: read

jobs:
  noop:
    runs-on: windows-2022

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    name: E2E Windows ${{ matrix.node-version }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - run: echo NOOP
