name: Verify Docs Quality
on:
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/verify_docs-quality.yml'
      - '**.md'

jobs:
  check-all-files:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # Vale does not support file excludes, so we use the script to generate a list of files instead
      # The action also does not allow args or a local config file to be passed in, so the files array
      # also contains an "--config=.github/vale/config.ini" option
      - name: generate vale args
        id: generate
        run: echo "args=$(node scripts/check-docs-quality.js --ci-args)" >> $GITHUB_OUTPUT

      - name: documentation quality check
        uses: errata-ai/vale-action@d89dee975228ae261d22c15adcd03578634d429c # v2.1.1
        with:
          # This also contains --config=.github/vale/config.ini ... :/
          files: '${{ steps.generate.outputs.args }}'
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Link Checker
        uses: lycheeverse/lychee-action@9f5e5c22c21c9b2981517972ed85e8b4785905a6 # v2.3.0
        with:
          args: >-
            --verbose
            --no-progress
            --exclude "npmjs\.com"
            --exclude "figma\.com"
            --exclude "localhost"
            --exclude "passportjs\.org"
            --retry 5
            --timeout 20
            './**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
