# NO-OP placeholder that always passes for other paths
# This is here so that we're able to set the status check as required

name: E2E Kubernetes Void
on:
  pull_request:
    paths-ignore:
      - 'yarn.lock'
      - '.github/workflows/verify_e2e-kubernetes.yml'
      - 'packages/backend-common/src/**'

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    name: Kubernetes ${{ matrix.node-version }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - run: echo NOOP
