name: Microsite Accessibility
on:
  # NOTE: If you change these you must update verify_microsite_accessibility-noop.yml as well
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/verify_microsite_accessibility.yml'
      - 'microsite/**'
      - 'beps/**'
      - 'mkdocs.yml'
      - 'docs/**'
jobs:
  lhci:
    name: Microsite Accessibility
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Use Node.js 22.x
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 22.x

      - name: top-level install
        run: yarn install --immutable

      - name: yarn install
        run: yarn install --immutable
        working-directory: microsite

      - name: run Lighthouse CI
        run: |
          yarn dlx @lhci/cli@0.11.x --config=microsite/lighthouserc.js autorun
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
