# Building on windows is really slow, so this workflow is separate from e2e.yml and only builds on changes
# to the cli itself. They're more likely to introduce issues on windows, compared to changes to core and yarn.lock.

name: E2E Windows
on:
  # NOTE: If you change these you must update verify_e2e-windows-noop.yml as well
  pull_request:
    paths:
      - 'yarn.lock'
      - '.github/workflows/verify_e2e-windows.yml'
      - 'packages/cli/**'
      - 'packages/e2e-test/**'
      - 'packages/create-app/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=8192

    name: E2E Windows ${{ matrix.node-version }}
    steps:
      # In order to have the create-app template function as if it was downloaded from NPM
      # we need to make sure we checkout files with LF line endings only
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email noreply@backstage.io
          git config --global user.name 'GitHub e2e user'

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup gyp env
        run: |
          echo 'GYP_MSVS_VERSION=2022' >> $Env:GITHUB_ENV
          echo 'GYP_MSVS_OVERRIDE_PATH=C:\\Dummy' >> $Env:GITHUB_ENV

      - name: Install latest gyp and set node-gyp path
        shell: powershell
        run: |
          npm prefix -g | % {npm config set npm_config_devdir "c:\temp\.gyp2"}
          npm install --global node-gyp@9.2.0
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}

      - name: setup chrome
        uses: browser-actions/setup-chrome@latest

      - name: yarn install
        run: yarn install --immutable

      - run: yarn tsc
      - run: yarn backstage-cli repo build
      - name: run E2E test
        run: yarn e2e-test run
        env:
          DEBUG: zombie
          CYPRESS_VERIFY_TIMEOUT: 600000
