name: Verify Microsite Next
on:
  pull_request:
    paths:
      - '.github/workflows/verify_microsite-next.yml'
      - 'microsite-next/**'
      - 'docs/**'

jobs:
  build-microsite:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096

    steps:
      - uses: actions/checkout@v3

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

        # Skip caching of microsite dependencies, it keeps the global cache size
        # smaller, which make Windows builds a lot faster for the rest of the project.
      - name: yarn install
        run: yarn install --immutable
        working-directory: microsite-next

      - name: verify yarn dependency duplicates
        run: node scripts/verify-lockfile-duplicates.js

      - name: prettier
        run: yarn prettier:check
        working-directory: microsite-next

      - name: build microsite-next
        run: yarn build
        working-directory: microsite-next
