name: Microsite
on:
  # NOTE: If you change these you must update verify_microsite-noop.yml as well
  pull_request:
    paths:
      - '.github/workflows/verify_microsite.yml'
      - 'microsite/**'
      - 'beps/**'
      - 'mkdocs.yml'
      - 'docs/**'

permissions:
  contents: read

jobs:
  build-microsite:
    runs-on: ubuntu-latest

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=8192
      DOCUSAURUS_SSR_CONCURRENCY: 5

    name: Microsite
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Use Node.js 20.x
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 20.x
      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
        with:
          python-version: '3.9'

      - name: Install MkDocs dependencies
        run: pip install mkdocs mkdocs-techdocs-core

        # Skip caching of microsite dependencies, it keeps the global cache size
        # smaller, which make Windows builds a lot faster for the rest of the project.
      - name: top-level install
        run: yarn install --immutable

      - name: yarn install
        run: yarn install --immutable
        working-directory: microsite

      - name: build API reference
        run: yarn build:api-docs

      - name: Build MkDocs for TechDocs
        run: mkdocs build --strict

      - name: verify yarn dependency duplicates
        run: node scripts/verify-lockfile-duplicates.js

      - name: prettier
        run: yarn prettier:check
        working-directory: microsite

      - name: build microsite
        run: yarn build
        working-directory: microsite
