# Building on windows is really slow, so this workflow is separate from e2e.yml and only builds on changes
# to the cli itself. They're more likely to introduce issues on windows, compared to changes to core and yarn.lock.

name: E2E Windows
on:
  # NOTE: If you change these you must update verify_e2e-windows-noop.yml as well
  pull_request:
    paths:
      - 'yarn.lock'
      - '.github/workflows/verify_e2e-windows.yml'
      - 'packages/cli/**'
      - 'packages/e2e-test/**'
      - 'packages/create-app/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=8192

    name: E2E Windows ${{ matrix.node-version }}
    steps:
      # In order to have the create-app template function as if it was downloaded from NPM
      # we need to make sure we checkout files with LF line endings only
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Configure Git
        run: |
          git config --global user.email noreply@backstage.io
          git config --global user.name 'GitHub e2e user'

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/ # Needed for auth

      - name: setup python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: '3.10'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@1ff57057b5cfdc39105cd07a01d78e9b0ea0c14c # v1.3.1

      - name: Setup gyp env
        run: |
          echo 'GYP_MSVS_VERSION=2022' >> $Env:GITHUB_ENV
          echo 'GYP_MSVS_OVERRIDE_PATH=C:\\Dummy' >> $Env:GITHUB_ENV

      - name: Install latest gyp and set node-gyp path
        shell: powershell
        run: |
          npm prefix -g | % {npm config set dev_dir "c:\temp\.gyp2"}
          npm prefix -g | % {npm config set node_gyp "$_\node_modules\node-gyp\bin\node-gyp.js"}

      - name: setup chrome
        uses: browser-actions/setup-chrome@803ef6dfb4fdf22089c9563225d95e4a515820a0 # latest

      - name: yarn install
        uses: backstage/actions/yarn-install@v0.6.4
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - run: yarn tsc
      - run: yarn backstage-cli repo build
      - name: run E2E test
        run: yarn e2e-test run
        env:
          DEBUG: zombie
          CYPRESS_VERIFY_TIMEOUT: 600000
