name: Microsite
on:
  # NOTE: If you change these you must update verify_microsite-noop.yml as well
  pull_request:
    paths:
      - '.github/workflows/verify_microsite.yml'
      - 'microsite/**'
      - 'beps/**'
      - 'mkdocs.yml'
      - 'docs/**'

permissions:
  contents: read

jobs:
  build-microsite:
    runs-on: ubuntu-latest

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=8192
      DOCUSAURUS_SSR_CONCURRENCY: 5

    name: Microsite
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: use node.js 18.x
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 18.x
      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
        with:
          python-version: '3.9'

      - name: Install MkDocs dependencies
        run: pip install mkdocs mkdocs-techdocs-core

        # Skip caching of microsite dependencies, it keeps the global cache size
        # smaller, which make Windows builds a lot faster for the rest of the project.
      - name: top-level install
        run: yarn install --immutable

      - name: yarn install
        run: yarn install --immutable
        working-directory: microsite

      - name: build API reference
        run: yarn build:api-docs

      - name: Build MkDocs for TechDocs
        run: mkdocs build --strict

      - name: verify yarn dependency duplicates
        run: node scripts/verify-lockfile-duplicates.js

      - name: prettier
        run: yarn prettier:check
        working-directory: microsite

      - name: build microsite
        run: yarn build
        working-directory: microsite
